name: "main workflow"

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "Hello World"
          input_version=${{ github.event.inputs.version }}

          declare -A images=(
            ["1.1"]="image-1.1"
            ["1.2"]="image-1.2"
            ["1.3"]="image-1.3"
          )

          if [ -z ${images[$input_version]} ]; then
            echo "there is no image tag"
            exit 1
          else
            image_tag=${images[$input_version]}
            echo $image_tag
          fi
