name: "main workflow"

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "Hello World"
          tmp="1.2"

          declare -A images=(
            ["1.1"]="image-1.1"
            ["1.2"]="image-1.2"
            ["1.3"]="image-1.3"
          )

          target=${images[$tmp]}
          echo $target
